
#import "LinkedInCreateNewContacts.h"
#import "LinkedInConstants.h"

@implementation LinkedInCreateNewContacts

static NSString * const sURLCreateNewContact = @"https://api.linkedin.com/v1/people/~/mailbox";

//TODO: This should be generated by JSON library and needs to contain an authorization token
static NSString * const sInviteJSON = @"{\"recipients\": {\"values\": [{\"person\": {\"_path\": \"/people/%@\"\"}}]},\"subject\": \"Invitation to connect.\",\"body\": \"Say yes!\",\"item-content\":{\"invitation-request\":{\"connect-type\":\"friend\"}}";

-( void )createNewContacts:( NSArray * )inContactIds error:( NSError ** )outError {
    for ( NSString * theContactId in inContactIds ) {
        [ mRequestor httpPost:sURLCreateNewContact
                   parameters:[ NSArray arrayWithObjects:sKeyFormat, sValueJSON, nil ]
                        error:outError ];
        if ( outError[ 0 ] != nil ) {
            break;
        }
    }
}

@end
